// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Kernloom Contributors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kernloom/adapter/v1/adapter.proto

package adapterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdapterService_Describe_FullMethodName                   = "/kernloom.adapter.v1.AdapterService/Describe"
	AdapterService_Health_FullMethodName                     = "/kernloom.adapter.v1.AdapterService/Health"
	AdapterService_PlanConfig_FullMethodName                 = "/kernloom.adapter.v1.AdapterService/PlanConfig"
	AdapterService_ValidateConfig_FullMethodName             = "/kernloom.adapter.v1.AdapterService/ValidateConfig"
	AdapterService_ReadObservedState_FullMethodName          = "/kernloom.adapter.v1.AdapterService/ReadObservedState"
	AdapterService_NormalizeState_FullMethodName             = "/kernloom.adapter.v1.AdapterService/NormalizeState"
	AdapterService_ProvideConformanceEvidence_FullMethodName = "/kernloom.adapter.v1.AdapterService/ProvideConformanceEvidence"
	AdapterService_ReadSignals_FullMethodName                = "/kernloom.adapter.v1.AdapterService/ReadSignals"
	AdapterService_StreamSignals_FullMethodName              = "/kernloom.adapter.v1.AdapterService/StreamSignals"
	AdapterService_ProvideRelationships_FullMethodName       = "/kernloom.adapter.v1.AdapterService/ProvideRelationships"
	AdapterService_ExecuteRuntimeAction_FullMethodName       = "/kernloom.adapter.v1.AdapterService/ExecuteRuntimeAction"
	AdapterService_GetRuntimeActionState_FullMethodName      = "/kernloom.adapter.v1.AdapterService/GetRuntimeActionState"
	AdapterService_RevokeRuntimeAction_FullMethodName        = "/kernloom.adapter.v1.AdapterService/RevokeRuntimeAction"
	AdapterService_ProvideAttestationEvidence_FullMethodName = "/kernloom.adapter.v1.AdapterService/ProvideAttestationEvidence"
)

// AdapterServiceClient is the client API for AdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterServiceClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	PlanConfig(ctx context.Context, in *PlanConfigRequest, opts ...grpc.CallOption) (*PlanConfigResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	ReadObservedState(ctx context.Context, in *ReadObservedStateRequest, opts ...grpc.CallOption) (*ReadObservedStateResponse, error)
	NormalizeState(ctx context.Context, in *NormalizeStateRequest, opts ...grpc.CallOption) (*NormalizeStateResponse, error)
	ProvideConformanceEvidence(ctx context.Context, in *ProvideConformanceEvidenceRequest, opts ...grpc.CallOption) (*ProvideConformanceEvidenceResponse, error)
	ReadSignals(ctx context.Context, in *ReadSignalsRequest, opts ...grpc.CallOption) (*ReadSignalsResponse, error)
	StreamSignals(ctx context.Context, in *StreamSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSignalsResponse], error)
	ProvideRelationships(ctx context.Context, in *ProvideRelationshipsRequest, opts ...grpc.CallOption) (*ProvideRelationshipsResponse, error)
	ExecuteRuntimeAction(ctx context.Context, in *ExecuteRuntimeActionRequest, opts ...grpc.CallOption) (*ExecuteRuntimeActionResponse, error)
	GetRuntimeActionState(ctx context.Context, in *GetRuntimeActionStateRequest, opts ...grpc.CallOption) (*GetRuntimeActionStateResponse, error)
	RevokeRuntimeAction(ctx context.Context, in *RevokeRuntimeActionRequest, opts ...grpc.CallOption) (*RevokeRuntimeActionResponse, error)
	ProvideAttestationEvidence(ctx context.Context, in *ProvideAttestationEvidenceRequest, opts ...grpc.CallOption) (*ProvideAttestationEvidenceResponse, error)
}

type adapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterServiceClient(cc grpc.ClientConnInterface) AdapterServiceClient {
	return &adapterServiceClient{cc}
}

func (c *adapterServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, AdapterService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AdapterService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) PlanConfig(ctx context.Context, in *PlanConfigRequest, opts ...grpc.CallOption) (*PlanConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanConfigResponse)
	err := c.cc.Invoke(ctx, AdapterService_PlanConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, AdapterService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) ReadObservedState(ctx context.Context, in *ReadObservedStateRequest, opts ...grpc.CallOption) (*ReadObservedStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadObservedStateResponse)
	err := c.cc.Invoke(ctx, AdapterService_ReadObservedState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) NormalizeState(ctx context.Context, in *NormalizeStateRequest, opts ...grpc.CallOption) (*NormalizeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NormalizeStateResponse)
	err := c.cc.Invoke(ctx, AdapterService_NormalizeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) ProvideConformanceEvidence(ctx context.Context, in *ProvideConformanceEvidenceRequest, opts ...grpc.CallOption) (*ProvideConformanceEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvideConformanceEvidenceResponse)
	err := c.cc.Invoke(ctx, AdapterService_ProvideConformanceEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) ReadSignals(ctx context.Context, in *ReadSignalsRequest, opts ...grpc.CallOption) (*ReadSignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSignalsResponse)
	err := c.cc.Invoke(ctx, AdapterService_ReadSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) StreamSignals(ctx context.Context, in *StreamSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSignalsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdapterService_ServiceDesc.Streams[0], AdapterService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSignalsRequest, StreamSignalsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdapterService_StreamSignalsClient = grpc.ServerStreamingClient[StreamSignalsResponse]

func (c *adapterServiceClient) ProvideRelationships(ctx context.Context, in *ProvideRelationshipsRequest, opts ...grpc.CallOption) (*ProvideRelationshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvideRelationshipsResponse)
	err := c.cc.Invoke(ctx, AdapterService_ProvideRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) ExecuteRuntimeAction(ctx context.Context, in *ExecuteRuntimeActionRequest, opts ...grpc.CallOption) (*ExecuteRuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteRuntimeActionResponse)
	err := c.cc.Invoke(ctx, AdapterService_ExecuteRuntimeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) GetRuntimeActionState(ctx context.Context, in *GetRuntimeActionStateRequest, opts ...grpc.CallOption) (*GetRuntimeActionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeActionStateResponse)
	err := c.cc.Invoke(ctx, AdapterService_GetRuntimeActionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) RevokeRuntimeAction(ctx context.Context, in *RevokeRuntimeActionRequest, opts ...grpc.CallOption) (*RevokeRuntimeActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRuntimeActionResponse)
	err := c.cc.Invoke(ctx, AdapterService_RevokeRuntimeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterServiceClient) ProvideAttestationEvidence(ctx context.Context, in *ProvideAttestationEvidenceRequest, opts ...grpc.CallOption) (*ProvideAttestationEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvideAttestationEvidenceResponse)
	err := c.cc.Invoke(ctx, AdapterService_ProvideAttestationEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServiceServer is the server API for AdapterService service.
// All implementations should embed UnimplementedAdapterServiceServer
// for forward compatibility.
type AdapterServiceServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	PlanConfig(context.Context, *PlanConfigRequest) (*PlanConfigResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	ReadObservedState(context.Context, *ReadObservedStateRequest) (*ReadObservedStateResponse, error)
	NormalizeState(context.Context, *NormalizeStateRequest) (*NormalizeStateResponse, error)
	ProvideConformanceEvidence(context.Context, *ProvideConformanceEvidenceRequest) (*ProvideConformanceEvidenceResponse, error)
	ReadSignals(context.Context, *ReadSignalsRequest) (*ReadSignalsResponse, error)
	StreamSignals(*StreamSignalsRequest, grpc.ServerStreamingServer[StreamSignalsResponse]) error
	ProvideRelationships(context.Context, *ProvideRelationshipsRequest) (*ProvideRelationshipsResponse, error)
	ExecuteRuntimeAction(context.Context, *ExecuteRuntimeActionRequest) (*ExecuteRuntimeActionResponse, error)
	GetRuntimeActionState(context.Context, *GetRuntimeActionStateRequest) (*GetRuntimeActionStateResponse, error)
	RevokeRuntimeAction(context.Context, *RevokeRuntimeActionRequest) (*RevokeRuntimeActionResponse, error)
	ProvideAttestationEvidence(context.Context, *ProvideAttestationEvidenceRequest) (*ProvideAttestationEvidenceResponse, error)
}

// UnimplementedAdapterServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterServiceServer struct{}

func (UnimplementedAdapterServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedAdapterServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAdapterServiceServer) PlanConfig(context.Context, *PlanConfigRequest) (*PlanConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanConfig not implemented")
}
func (UnimplementedAdapterServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedAdapterServiceServer) ReadObservedState(context.Context, *ReadObservedStateRequest) (*ReadObservedStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadObservedState not implemented")
}
func (UnimplementedAdapterServiceServer) NormalizeState(context.Context, *NormalizeStateRequest) (*NormalizeStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NormalizeState not implemented")
}
func (UnimplementedAdapterServiceServer) ProvideConformanceEvidence(context.Context, *ProvideConformanceEvidenceRequest) (*ProvideConformanceEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvideConformanceEvidence not implemented")
}
func (UnimplementedAdapterServiceServer) ReadSignals(context.Context, *ReadSignalsRequest) (*ReadSignalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSignals not implemented")
}
func (UnimplementedAdapterServiceServer) StreamSignals(*StreamSignalsRequest, grpc.ServerStreamingServer[StreamSignalsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedAdapterServiceServer) ProvideRelationships(context.Context, *ProvideRelationshipsRequest) (*ProvideRelationshipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvideRelationships not implemented")
}
func (UnimplementedAdapterServiceServer) ExecuteRuntimeAction(context.Context, *ExecuteRuntimeActionRequest) (*ExecuteRuntimeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteRuntimeAction not implemented")
}
func (UnimplementedAdapterServiceServer) GetRuntimeActionState(context.Context, *GetRuntimeActionStateRequest) (*GetRuntimeActionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeActionState not implemented")
}
func (UnimplementedAdapterServiceServer) RevokeRuntimeAction(context.Context, *RevokeRuntimeActionRequest) (*RevokeRuntimeActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRuntimeAction not implemented")
}
func (UnimplementedAdapterServiceServer) ProvideAttestationEvidence(context.Context, *ProvideAttestationEvidenceRequest) (*ProvideAttestationEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvideAttestationEvidence not implemented")
}
func (UnimplementedAdapterServiceServer) testEmbeddedByValue() {}

// UnsafeAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterServiceServer will
// result in compilation errors.
type UnsafeAdapterServiceServer interface {
	mustEmbedUnimplementedAdapterServiceServer()
}

func RegisterAdapterServiceServer(s grpc.ServiceRegistrar, srv AdapterServiceServer) {
	// If the following call panics, it indicates UnimplementedAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdapterService_ServiceDesc, srv)
}

func _AdapterService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_PlanConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).PlanConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_PlanConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).PlanConfig(ctx, req.(*PlanConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_ReadObservedState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadObservedStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ReadObservedState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ReadObservedState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ReadObservedState(ctx, req.(*ReadObservedStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_NormalizeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NormalizeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).NormalizeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_NormalizeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).NormalizeState(ctx, req.(*NormalizeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_ProvideConformanceEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideConformanceEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ProvideConformanceEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ProvideConformanceEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ProvideConformanceEvidence(ctx, req.(*ProvideConformanceEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_ReadSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ReadSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ReadSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ReadSignals(ctx, req.(*ReadSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSignalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdapterServiceServer).StreamSignals(m, &grpc.GenericServerStream[StreamSignalsRequest, StreamSignalsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdapterService_StreamSignalsServer = grpc.ServerStreamingServer[StreamSignalsResponse]

func _AdapterService_ProvideRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ProvideRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ProvideRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ProvideRelationships(ctx, req.(*ProvideRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_ExecuteRuntimeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRuntimeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ExecuteRuntimeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ExecuteRuntimeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ExecuteRuntimeAction(ctx, req.(*ExecuteRuntimeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_GetRuntimeActionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeActionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).GetRuntimeActionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_GetRuntimeActionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).GetRuntimeActionState(ctx, req.(*GetRuntimeActionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_RevokeRuntimeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRuntimeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).RevokeRuntimeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_RevokeRuntimeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).RevokeRuntimeAction(ctx, req.(*RevokeRuntimeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterService_ProvideAttestationEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideAttestationEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServiceServer).ProvideAttestationEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterService_ProvideAttestationEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServiceServer).ProvideAttestationEvidence(ctx, req.(*ProvideAttestationEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterService_ServiceDesc is the grpc.ServiceDesc for AdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kernloom.adapter.v1.AdapterService",
	HandlerType: (*AdapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _AdapterService_Describe_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AdapterService_Health_Handler,
		},
		{
			MethodName: "PlanConfig",
			Handler:    _AdapterService_PlanConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _AdapterService_ValidateConfig_Handler,
		},
		{
			MethodName: "ReadObservedState",
			Handler:    _AdapterService_ReadObservedState_Handler,
		},
		{
			MethodName: "NormalizeState",
			Handler:    _AdapterService_NormalizeState_Handler,
		},
		{
			MethodName: "ProvideConformanceEvidence",
			Handler:    _AdapterService_ProvideConformanceEvidence_Handler,
		},
		{
			MethodName: "ReadSignals",
			Handler:    _AdapterService_ReadSignals_Handler,
		},
		{
			MethodName: "ProvideRelationships",
			Handler:    _AdapterService_ProvideRelationships_Handler,
		},
		{
			MethodName: "ExecuteRuntimeAction",
			Handler:    _AdapterService_ExecuteRuntimeAction_Handler,
		},
		{
			MethodName: "GetRuntimeActionState",
			Handler:    _AdapterService_GetRuntimeActionState_Handler,
		},
		{
			MethodName: "RevokeRuntimeAction",
			Handler:    _AdapterService_RevokeRuntimeAction_Handler,
		},
		{
			MethodName: "ProvideAttestationEvidence",
			Handler:    _AdapterService_ProvideAttestationEvidence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _AdapterService_StreamSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kernloom/adapter/v1/adapter.proto",
}
