// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Kernloom Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kernloom/adapter/v1/adapter.proto

package adapterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adapter       *AdapterDescriptor     `protobuf:"bytes,1,opt,name=adapter,proto3" json:"adapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetAdapter() *AdapterDescriptor {
	if x != nil {
		return x.Adapter
	}
	return nil
}

type AdapterDescriptor struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	AdapterId           string                          `protobuf:"bytes,1,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	Name                string                          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProtocolVersion     string                          `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities        []*CapabilityDescriptor         `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ContextRequirements []*ContextRequirementDescriptor `protobuf:"bytes,5,rep,name=context_requirements,json=contextRequirements,proto3" json:"context_requirements,omitempty"`
	Privileges          []*PrivilegeDescriptor          `protobuf:"bytes,6,rep,name=privileges,proto3" json:"privileges,omitempty"`
	Facets              []string                        `protobuf:"bytes,7,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdapterDescriptor) Reset() {
	*x = AdapterDescriptor{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterDescriptor) ProtoMessage() {}

func (x *AdapterDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterDescriptor.ProtoReflect.Descriptor instead.
func (*AdapterDescriptor) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *AdapterDescriptor) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *AdapterDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdapterDescriptor) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AdapterDescriptor) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AdapterDescriptor) GetContextRequirements() []*ContextRequirementDescriptor {
	if x != nil {
		return x.ContextRequirements
	}
	return nil
}

func (x *AdapterDescriptor) GetPrivileges() []*PrivilegeDescriptor {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *AdapterDescriptor) GetFacets() []string {
	if x != nil {
		return x.Facets
	}
	return nil
}

type CapabilityDescriptor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Actions        []string               `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	RuntimeActions []string               `protobuf:"bytes,5,rep,name=runtime_actions,json=runtimeActions,proto3" json:"runtime_actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *CapabilityDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CapabilityDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CapabilityDescriptor) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CapabilityDescriptor) GetRuntimeActions() []string {
	if x != nil {
		return x.RuntimeActions
	}
	return nil
}

type ContextRequirementDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fact          string                 `protobuf:"bytes,1,opt,name=fact,proto3" json:"fact,omitempty"`
	Freshness     string                 `protobuf:"bytes,2,opt,name=freshness,proto3" json:"freshness,omitempty"`
	Confidence    string                 `protobuf:"bytes,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Sensitivity   string                 `protobuf:"bytes,4,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequirementDescriptor) Reset() {
	*x = ContextRequirementDescriptor{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequirementDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequirementDescriptor) ProtoMessage() {}

func (x *ContextRequirementDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequirementDescriptor.ProtoReflect.Descriptor instead.
func (*ContextRequirementDescriptor) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *ContextRequirementDescriptor) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

func (x *ContextRequirementDescriptor) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

func (x *ContextRequirementDescriptor) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *ContextRequirementDescriptor) GetSensitivity() string {
	if x != nil {
		return x.Sensitivity
	}
	return ""
}

type PrivilegeDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Access        string                 `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivilegeDescriptor) Reset() {
	*x = PrivilegeDescriptor{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegeDescriptor) ProtoMessage() {}

func (x *PrivilegeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegeDescriptor.ProtoReflect.Descriptor instead.
func (*PrivilegeDescriptor) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *PrivilegeDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrivilegeDescriptor) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PrivilegeDescriptor) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PrivilegeDescriptor) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlanConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PolicyId       string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	SourceCommit   string                 `protobuf:"bytes,2,opt,name=source_commit,json=sourceCommit,proto3" json:"source_commit,omitempty"`
	ResolvedPolicy []byte                 `protobuf:"bytes,3,opt,name=resolved_policy,json=resolvedPolicy,proto3" json:"resolved_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanConfigRequest) Reset() {
	*x = PlanConfigRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanConfigRequest) ProtoMessage() {}

func (x *PlanConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanConfigRequest.ProtoReflect.Descriptor instead.
func (*PlanConfigRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{8}
}

func (x *PlanConfigRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PlanConfigRequest) GetSourceCommit() string {
	if x != nil {
		return x.SourceCommit
	}
	return ""
}

func (x *PlanConfigRequest) GetResolvedPolicy() []byte {
	if x != nil {
		return x.ResolvedPolicy
	}
	return nil
}

type PlanConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposedChanges []*ConfigChange        `protobuf:"bytes,1,rep,name=proposed_changes,json=proposedChanges,proto3" json:"proposed_changes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanConfigResponse) Reset() {
	*x = PlanConfigResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanConfigResponse) ProtoMessage() {}

func (x *PlanConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanConfigResponse.ProtoReflect.Descriptor instead.
func (*PlanConfigResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{9}
}

func (x *PlanConfigResponse) GetProposedChanges() []*ConfigChange {
	if x != nil {
		return x.ProposedChanges
	}
	return nil
}

type ConfigChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetObject  string                 `protobuf:"bytes,2,opt,name=target_object,json=targetObject,proto3" json:"target_object,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChange) Reset() {
	*x = ConfigChange{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChange) ProtoMessage() {}

func (x *ConfigChange) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChange.ProtoReflect.Descriptor instead.
func (*ConfigChange) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigChange) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigChange) GetTargetObject() string {
	if x != nil {
		return x.TargetObject
	}
	return ""
}

func (x *ConfigChange) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConfigChange) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ValidateConfigRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposedChanges []*ConfigChange        `protobuf:"bytes,1,rep,name=proposed_changes,json=proposedChanges,proto3" json:"proposed_changes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateConfigRequest) GetProposedChanges() []*ConfigChange {
	if x != nil {
		return x.ProposedChanges
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateConfigResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type ReadObservedStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadObservedStateRequest) Reset() {
	*x = ReadObservedStateRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadObservedStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadObservedStateRequest) ProtoMessage() {}

func (x *ReadObservedStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadObservedStateRequest.ProtoReflect.Descriptor instead.
func (*ReadObservedStateRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{13}
}

func (x *ReadObservedStateRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ReadObservedStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObservedObject      `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadObservedStateResponse) Reset() {
	*x = ReadObservedStateResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadObservedStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadObservedStateResponse) ProtoMessage() {}

func (x *ReadObservedStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadObservedStateResponse.ProtoReflect.Descriptor instead.
func (*ReadObservedStateResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{14}
}

func (x *ReadObservedStateResponse) GetObjects() []*ObservedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ObservedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	State         []byte                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedObject) Reset() {
	*x = ObservedObject{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedObject) ProtoMessage() {}

func (x *ObservedObject) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedObject.ProtoReflect.Descriptor instead.
func (*ObservedObject) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{15}
}

func (x *ObservedObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObservedObject) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObservedObject) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type NormalizeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObservedObject      `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizeStateRequest) Reset() {
	*x = NormalizeStateRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeStateRequest) ProtoMessage() {}

func (x *NormalizeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeStateRequest.ProtoReflect.Descriptor instead.
func (*NormalizeStateRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{16}
}

func (x *NormalizeStateRequest) GetObjects() []*ObservedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type NormalizeStateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NormalizedObjects []*ObservedObject      `protobuf:"bytes,1,rep,name=normalized_objects,json=normalizedObjects,proto3" json:"normalized_objects,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NormalizeStateResponse) Reset() {
	*x = NormalizeStateResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeStateResponse) ProtoMessage() {}

func (x *NormalizeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizeStateResponse.ProtoReflect.Descriptor instead.
func (*NormalizeStateResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{17}
}

func (x *NormalizeStateResponse) GetNormalizedObjects() []*ObservedObject {
	if x != nil {
		return x.NormalizedObjects
	}
	return nil
}

type ProvideConformanceEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideConformanceEvidenceRequest) Reset() {
	*x = ProvideConformanceEvidenceRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideConformanceEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideConformanceEvidenceRequest) ProtoMessage() {}

func (x *ProvideConformanceEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideConformanceEvidenceRequest.ProtoReflect.Descriptor instead.
func (*ProvideConformanceEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{18}
}

func (x *ProvideConformanceEvidenceRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ProvideConformanceEvidenceRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ProvideConformanceEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      []*Evidence            `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideConformanceEvidenceResponse) Reset() {
	*x = ProvideConformanceEvidenceResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideConformanceEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideConformanceEvidenceResponse) ProtoMessage() {}

func (x *ProvideConformanceEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideConformanceEvidenceResponse.ProtoReflect.Descriptor instead.
func (*ProvideConformanceEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{19}
}

func (x *ProvideConformanceEvidenceResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ReadSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSignalsRequest) Reset() {
	*x = ReadSignalsRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSignalsRequest) ProtoMessage() {}

func (x *ReadSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSignalsRequest.ProtoReflect.Descriptor instead.
func (*ReadSignalsRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{20}
}

func (x *ReadSignalsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ReadSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSignalsResponse) Reset() {
	*x = ReadSignalsResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSignalsResponse) ProtoMessage() {}

func (x *ReadSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSignalsResponse.ProtoReflect.Descriptor instead.
func (*ReadSignalsResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{21}
}

func (x *ReadSignalsResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

type StreamSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSignalsRequest) Reset() {
	*x = StreamSignalsRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSignalsRequest) ProtoMessage() {}

func (x *StreamSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSignalsRequest.ProtoReflect.Descriptor instead.
func (*StreamSignalsRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{22}
}

func (x *StreamSignalsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type StreamSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *Signal                `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSignalsResponse) Reset() {
	*x = StreamSignalsResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSignalsResponse) ProtoMessage() {}

func (x *StreamSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSignalsResponse.ProtoReflect.Descriptor instead.
func (*StreamSignalsResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{23}
}

func (x *StreamSignalsResponse) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{24}
}

func (x *Signal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Signal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Signal) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Signal) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProvideRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideRelationshipsRequest) Reset() {
	*x = ProvideRelationshipsRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideRelationshipsRequest) ProtoMessage() {}

func (x *ProvideRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*ProvideRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{25}
}

func (x *ProvideRelationshipsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ProvideRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*Relationship        `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideRelationshipsResponse) Reset() {
	*x = ProvideRelationshipsResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideRelationshipsResponse) ProtoMessage() {}

func (x *ProvideRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*ProvideRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{26}
}

func (x *ProvideRelationshipsResponse) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type Relationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate     string                 `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{27}
}

func (x *Relationship) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Relationship) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *Relationship) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type ExecuteRuntimeActionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RuntimeActionId   string                 `protobuf:"bytes,1,opt,name=runtime_action_id,json=runtimeActionId,proto3" json:"runtime_action_id,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ActionType        string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	TargetScope       string                 `protobuf:"bytes,4,opt,name=target_scope,json=targetScope,proto3" json:"target_scope,omitempty"`
	TargetKey         string                 `protobuf:"bytes,5,opt,name=target_key,json=targetKey,proto3" json:"target_key,omitempty"`
	Ttl               string                 `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Reason            string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	AuditId           string                 `protobuf:"bytes,8,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	SourceCommit      string                 `protobuf:"bytes,9,opt,name=source_commit,json=sourceCommit,proto3" json:"source_commit,omitempty"`
	CapabilityGrantId string                 `protobuf:"bytes,10,opt,name=capability_grant_id,json=capabilityGrantId,proto3" json:"capability_grant_id,omitempty"`
	SignedBundle      []byte                 `protobuf:"bytes,11,opt,name=signed_bundle,json=signedBundle,proto3" json:"signed_bundle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteRuntimeActionRequest) Reset() {
	*x = ExecuteRuntimeActionRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRuntimeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRuntimeActionRequest) ProtoMessage() {}

func (x *ExecuteRuntimeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRuntimeActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRuntimeActionRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{28}
}

func (x *ExecuteRuntimeActionRequest) GetRuntimeActionId() string {
	if x != nil {
		return x.RuntimeActionId
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetTargetScope() string {
	if x != nil {
		return x.TargetScope
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetTargetKey() string {
	if x != nil {
		return x.TargetKey
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetSourceCommit() string {
	if x != nil {
		return x.SourceCommit
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetCapabilityGrantId() string {
	if x != nil {
		return x.CapabilityGrantId
	}
	return ""
}

func (x *ExecuteRuntimeActionRequest) GetSignedBundle() []byte {
	if x != nil {
		return x.SignedBundle
	}
	return nil
}

type ExecuteRuntimeActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRuntimeActionResponse) Reset() {
	*x = ExecuteRuntimeActionResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRuntimeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRuntimeActionResponse) ProtoMessage() {}

func (x *ExecuteRuntimeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRuntimeActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteRuntimeActionResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{29}
}

func (x *ExecuteRuntimeActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteRuntimeActionResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type GetRuntimeActionStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRuntimeActionStateRequest) Reset() {
	*x = GetRuntimeActionStateRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeActionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeActionStateRequest) ProtoMessage() {}

func (x *GetRuntimeActionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeActionStateRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeActionStateRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{30}
}

func (x *GetRuntimeActionStateRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetRuntimeActionStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeActionStateResponse) Reset() {
	*x = GetRuntimeActionStateResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeActionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeActionStateResponse) ProtoMessage() {}

func (x *GetRuntimeActionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeActionStateResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeActionStateResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{31}
}

func (x *GetRuntimeActionStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetRuntimeActionStateResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type RevokeRuntimeActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AuditId        string                 `protobuf:"bytes,3,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeRuntimeActionRequest) Reset() {
	*x = RevokeRuntimeActionRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRuntimeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRuntimeActionRequest) ProtoMessage() {}

func (x *RevokeRuntimeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRuntimeActionRequest.ProtoReflect.Descriptor instead.
func (*RevokeRuntimeActionRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{32}
}

func (x *RevokeRuntimeActionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RevokeRuntimeActionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeRuntimeActionRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

type RevokeRuntimeActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRuntimeActionResponse) Reset() {
	*x = RevokeRuntimeActionResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRuntimeActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRuntimeActionResponse) ProtoMessage() {}

func (x *RevokeRuntimeActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRuntimeActionResponse.ProtoReflect.Descriptor instead.
func (*RevokeRuntimeActionResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{33}
}

func (x *RevokeRuntimeActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RevokeRuntimeActionResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ProvideAttestationEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideAttestationEvidenceRequest) Reset() {
	*x = ProvideAttestationEvidenceRequest{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideAttestationEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideAttestationEvidenceRequest) ProtoMessage() {}

func (x *ProvideAttestationEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideAttestationEvidenceRequest.ProtoReflect.Descriptor instead.
func (*ProvideAttestationEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{34}
}

func (x *ProvideAttestationEvidenceRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ProvideAttestationEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      []*Evidence            `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideAttestationEvidenceResponse) Reset() {
	*x = ProvideAttestationEvidenceResponse{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideAttestationEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideAttestationEvidenceResponse) ProtoMessage() {}

func (x *ProvideAttestationEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideAttestationEvidenceResponse.ProtoReflect.Descriptor instead.
func (*ProvideAttestationEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{35}
}

func (x *ProvideAttestationEvidenceResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Freshness     string                 `protobuf:"bytes,4,opt,name=freshness,proto3" json:"freshness,omitempty"`
	Confidence    string                 `protobuf:"bytes,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{36}
}

func (x *Evidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evidence) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Evidence) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Evidence) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

func (x *Evidence) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *Evidence) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_kernloom_adapter_v1_adapter_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_kernloom_adapter_v1_adapter_proto_rawDescGZIP(), []int{37}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kernloom_adapter_v1_adapter_proto protoreflect.FileDescriptor

const file_kernloom_adapter_v1_adapter_proto_rawDesc = "" +
	"\n" +
	"!kernloom/adapter/v1/adapter.proto\x12\x13kernloom.adapter.v1\"\x11\n" +
	"\x0fDescribeRequest\"T\n" +
	"\x10DescribeResponse\x12@\n" +
	"\aadapter\x18\x01 \x01(\v2&.kernloom.adapter.v1.AdapterDescriptorR\aadapter\"\x88\x03\n" +
	"\x11AdapterDescriptor\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x01 \x01(\tR\tadapterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12M\n" +
	"\fcapabilities\x18\x04 \x03(\v2).kernloom.adapter.v1.CapabilityDescriptorR\fcapabilities\x12d\n" +
	"\x14context_requirements\x18\x05 \x03(\v21.kernloom.adapter.v1.ContextRequirementDescriptorR\x13contextRequirements\x12H\n" +
	"\n" +
	"privileges\x18\x06 \x03(\v2(.kernloom.adapter.v1.PrivilegeDescriptorR\n" +
	"privileges\x12\x16\n" +
	"\x06facets\x18\a \x03(\tR\x06facets\"\xa0\x01\n" +
	"\x14CapabilityDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\aactions\x18\x04 \x03(\tR\aactions\x12'\n" +
	"\x0fruntime_actions\x18\x05 \x03(\tR\x0eruntimeActions\"\x92\x01\n" +
	"\x1cContextRequirementDescriptor\x12\x12\n" +
	"\x04fact\x18\x01 \x01(\tR\x04fact\x12\x1c\n" +
	"\tfreshness\x18\x02 \x01(\tR\tfreshness\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\tR\n" +
	"confidence\x12 \n" +
	"\vsensitivity\x18\x04 \x01(\tR\vsensitivity\"k\n" +
	"\x13PrivilegeDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x16\n" +
	"\x06access\x18\x04 \x01(\tR\x06access\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"~\n" +
	"\x11PlanConfigRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12#\n" +
	"\rsource_commit\x18\x02 \x01(\tR\fsourceCommit\x12'\n" +
	"\x0fresolved_policy\x18\x03 \x01(\fR\x0eresolvedPolicy\"b\n" +
	"\x12PlanConfigResponse\x12L\n" +
	"\x10proposed_changes\x18\x01 \x03(\v2!.kernloom.adapter.v1.ConfigChangeR\x0fproposedChanges\"u\n" +
	"\fConfigChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rtarget_object\x18\x02 \x01(\tR\ftargetObject\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"e\n" +
	"\x15ValidateConfigRequest\x12L\n" +
	"\x10proposed_changes\x18\x01 \x03(\v2!.kernloom.adapter.v1.ConfigChangeR\x0fproposedChanges\"R\n" +
	"\x16ValidateConfigResponse\x128\n" +
	"\bfindings\x18\x01 \x03(\v2\x1c.kernloom.adapter.v1.FindingR\bfindings\"0\n" +
	"\x18ReadObservedStateRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"Z\n" +
	"\x19ReadObservedStateResponse\x12=\n" +
	"\aobjects\x18\x01 \x03(\v2#.kernloom.adapter.v1.ObservedObjectR\aobjects\"J\n" +
	"\x0eObservedObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x03 \x01(\fR\x05state\"V\n" +
	"\x15NormalizeStateRequest\x12=\n" +
	"\aobjects\x18\x01 \x03(\v2#.kernloom.adapter.v1.ObservedObjectR\aobjects\"l\n" +
	"\x16NormalizeStateResponse\x12R\n" +
	"\x12normalized_objects\x18\x01 \x03(\v2#.kernloom.adapter.v1.ObservedObjectR\x11normalizedObjects\"a\n" +
	"!ProvideConformanceEvidenceRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"_\n" +
	"\"ProvideConformanceEvidenceResponse\x129\n" +
	"\bevidence\x18\x01 \x03(\v2\x1d.kernloom.adapter.v1.EvidenceR\bevidence\"*\n" +
	"\x12ReadSignalsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"L\n" +
	"\x13ReadSignalsResponse\x125\n" +
	"\asignals\x18\x01 \x03(\v2\x1b.kernloom.adapter.v1.SignalR\asignals\",\n" +
	"\x14StreamSignalsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"L\n" +
	"\x15StreamSignalsResponse\x123\n" +
	"\x06signal\x18\x01 \x01(\v2\x1b.kernloom.adapter.v1.SignalR\x06signal\"t\n" +
	"\x06Signal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"3\n" +
	"\x1bProvideRelationshipsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"g\n" +
	"\x1cProvideRelationshipsResponse\x12G\n" +
	"\rrelationships\x18\x01 \x03(\v2!.kernloom.adapter.v1.RelationshipR\rrelationships\"^\n" +
	"\fRelationship\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1c\n" +
	"\tpredicate\x18\x02 \x01(\tR\tpredicate\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"\x94\x03\n" +
	"\x1bExecuteRuntimeActionRequest\x12*\n" +
	"\x11runtime_action_id\x18\x01 \x01(\tR\x0fruntimeActionId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\ftarget_scope\x18\x04 \x01(\tR\vtargetScope\x12\x1d\n" +
	"\n" +
	"target_key\x18\x05 \x01(\tR\ttargetKey\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\tR\x03ttl\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x19\n" +
	"\baudit_id\x18\b \x01(\tR\aauditId\x12#\n" +
	"\rsource_commit\x18\t \x01(\tR\fsourceCommit\x12.\n" +
	"\x13capability_grant_id\x18\n" +
	" \x01(\tR\x11capabilityGrantId\x12#\n" +
	"\rsigned_bundle\x18\v \x01(\fR\fsignedBundle\"q\n" +
	"\x1cExecuteRuntimeActionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\bevidence\x18\x02 \x03(\v2\x1d.kernloom.adapter.v1.EvidenceR\bevidence\"G\n" +
	"\x1cGetRuntimeActionStateRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"r\n" +
	"\x1dGetRuntimeActionStateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\bevidence\x18\x02 \x03(\v2\x1d.kernloom.adapter.v1.EvidenceR\bevidence\"x\n" +
	"\x1aRevokeRuntimeActionRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\baudit_id\x18\x03 \x01(\tR\aauditId\"p\n" +
	"\x1bRevokeRuntimeActionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\bevidence\x18\x02 \x03(\v2\x1d.kernloom.adapter.v1.EvidenceR\bevidence\"<\n" +
	"!ProvideAttestationEvidenceRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"_\n" +
	"\"ProvideAttestationEvidenceResponse\x129\n" +
	"\bevidence\x18\x01 \x03(\v2\x1d.kernloom.adapter.v1.EvidenceR\bevidence\"\xa0\x01\n" +
	"\bEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1c\n" +
	"\tfreshness\x18\x04 \x01(\tR\tfreshness\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\tR\n" +
	"confidence\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"c\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xc5\f\n" +
	"\x0eAdapterService\x12W\n" +
	"\bDescribe\x12$.kernloom.adapter.v1.DescribeRequest\x1a%.kernloom.adapter.v1.DescribeResponse\x12Q\n" +
	"\x06Health\x12\".kernloom.adapter.v1.HealthRequest\x1a#.kernloom.adapter.v1.HealthResponse\x12]\n" +
	"\n" +
	"PlanConfig\x12&.kernloom.adapter.v1.PlanConfigRequest\x1a'.kernloom.adapter.v1.PlanConfigResponse\x12i\n" +
	"\x0eValidateConfig\x12*.kernloom.adapter.v1.ValidateConfigRequest\x1a+.kernloom.adapter.v1.ValidateConfigResponse\x12r\n" +
	"\x11ReadObservedState\x12-.kernloom.adapter.v1.ReadObservedStateRequest\x1a..kernloom.adapter.v1.ReadObservedStateResponse\x12i\n" +
	"\x0eNormalizeState\x12*.kernloom.adapter.v1.NormalizeStateRequest\x1a+.kernloom.adapter.v1.NormalizeStateResponse\x12\x8d\x01\n" +
	"\x1aProvideConformanceEvidence\x126.kernloom.adapter.v1.ProvideConformanceEvidenceRequest\x1a7.kernloom.adapter.v1.ProvideConformanceEvidenceResponse\x12`\n" +
	"\vReadSignals\x12'.kernloom.adapter.v1.ReadSignalsRequest\x1a(.kernloom.adapter.v1.ReadSignalsResponse\x12h\n" +
	"\rStreamSignals\x12).kernloom.adapter.v1.StreamSignalsRequest\x1a*.kernloom.adapter.v1.StreamSignalsResponse0\x01\x12{\n" +
	"\x14ProvideRelationships\x120.kernloom.adapter.v1.ProvideRelationshipsRequest\x1a1.kernloom.adapter.v1.ProvideRelationshipsResponse\x12{\n" +
	"\x14ExecuteRuntimeAction\x120.kernloom.adapter.v1.ExecuteRuntimeActionRequest\x1a1.kernloom.adapter.v1.ExecuteRuntimeActionResponse\x12~\n" +
	"\x15GetRuntimeActionState\x121.kernloom.adapter.v1.GetRuntimeActionStateRequest\x1a2.kernloom.adapter.v1.GetRuntimeActionStateResponse\x12x\n" +
	"\x13RevokeRuntimeAction\x12/.kernloom.adapter.v1.RevokeRuntimeActionRequest\x1a0.kernloom.adapter.v1.RevokeRuntimeActionResponse\x12\x8d\x01\n" +
	"\x1aProvideAttestationEvidence\x126.kernloom.adapter.v1.ProvideAttestationEvidenceRequest\x1a7.kernloom.adapter.v1.ProvideAttestationEvidenceResponseBCZAgithub.com/kernloom/kernloom-protocol/sdk/go/adapter/v1;adapterv1b\x06proto3"

var (
	file_kernloom_adapter_v1_adapter_proto_rawDescOnce sync.Once
	file_kernloom_adapter_v1_adapter_proto_rawDescData []byte
)

func file_kernloom_adapter_v1_adapter_proto_rawDescGZIP() []byte {
	file_kernloom_adapter_v1_adapter_proto_rawDescOnce.Do(func() {
		file_kernloom_adapter_v1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernloom_adapter_v1_adapter_proto_rawDesc), len(file_kernloom_adapter_v1_adapter_proto_rawDesc)))
	})
	return file_kernloom_adapter_v1_adapter_proto_rawDescData
}

var file_kernloom_adapter_v1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_kernloom_adapter_v1_adapter_proto_goTypes = []any{
	(*DescribeRequest)(nil),                    // 0: kernloom.adapter.v1.DescribeRequest
	(*DescribeResponse)(nil),                   // 1: kernloom.adapter.v1.DescribeResponse
	(*AdapterDescriptor)(nil),                  // 2: kernloom.adapter.v1.AdapterDescriptor
	(*CapabilityDescriptor)(nil),               // 3: kernloom.adapter.v1.CapabilityDescriptor
	(*ContextRequirementDescriptor)(nil),       // 4: kernloom.adapter.v1.ContextRequirementDescriptor
	(*PrivilegeDescriptor)(nil),                // 5: kernloom.adapter.v1.PrivilegeDescriptor
	(*HealthRequest)(nil),                      // 6: kernloom.adapter.v1.HealthRequest
	(*HealthResponse)(nil),                     // 7: kernloom.adapter.v1.HealthResponse
	(*PlanConfigRequest)(nil),                  // 8: kernloom.adapter.v1.PlanConfigRequest
	(*PlanConfigResponse)(nil),                 // 9: kernloom.adapter.v1.PlanConfigResponse
	(*ConfigChange)(nil),                       // 10: kernloom.adapter.v1.ConfigChange
	(*ValidateConfigRequest)(nil),              // 11: kernloom.adapter.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),             // 12: kernloom.adapter.v1.ValidateConfigResponse
	(*ReadObservedStateRequest)(nil),           // 13: kernloom.adapter.v1.ReadObservedStateRequest
	(*ReadObservedStateResponse)(nil),          // 14: kernloom.adapter.v1.ReadObservedStateResponse
	(*ObservedObject)(nil),                     // 15: kernloom.adapter.v1.ObservedObject
	(*NormalizeStateRequest)(nil),              // 16: kernloom.adapter.v1.NormalizeStateRequest
	(*NormalizeStateResponse)(nil),             // 17: kernloom.adapter.v1.NormalizeStateResponse
	(*ProvideConformanceEvidenceRequest)(nil),  // 18: kernloom.adapter.v1.ProvideConformanceEvidenceRequest
	(*ProvideConformanceEvidenceResponse)(nil), // 19: kernloom.adapter.v1.ProvideConformanceEvidenceResponse
	(*ReadSignalsRequest)(nil),                 // 20: kernloom.adapter.v1.ReadSignalsRequest
	(*ReadSignalsResponse)(nil),                // 21: kernloom.adapter.v1.ReadSignalsResponse
	(*StreamSignalsRequest)(nil),               // 22: kernloom.adapter.v1.StreamSignalsRequest
	(*StreamSignalsResponse)(nil),              // 23: kernloom.adapter.v1.StreamSignalsResponse
	(*Signal)(nil),                             // 24: kernloom.adapter.v1.Signal
	(*ProvideRelationshipsRequest)(nil),        // 25: kernloom.adapter.v1.ProvideRelationshipsRequest
	(*ProvideRelationshipsResponse)(nil),       // 26: kernloom.adapter.v1.ProvideRelationshipsResponse
	(*Relationship)(nil),                       // 27: kernloom.adapter.v1.Relationship
	(*ExecuteRuntimeActionRequest)(nil),        // 28: kernloom.adapter.v1.ExecuteRuntimeActionRequest
	(*ExecuteRuntimeActionResponse)(nil),       // 29: kernloom.adapter.v1.ExecuteRuntimeActionResponse
	(*GetRuntimeActionStateRequest)(nil),       // 30: kernloom.adapter.v1.GetRuntimeActionStateRequest
	(*GetRuntimeActionStateResponse)(nil),      // 31: kernloom.adapter.v1.GetRuntimeActionStateResponse
	(*RevokeRuntimeActionRequest)(nil),         // 32: kernloom.adapter.v1.RevokeRuntimeActionRequest
	(*RevokeRuntimeActionResponse)(nil),        // 33: kernloom.adapter.v1.RevokeRuntimeActionResponse
	(*ProvideAttestationEvidenceRequest)(nil),  // 34: kernloom.adapter.v1.ProvideAttestationEvidenceRequest
	(*ProvideAttestationEvidenceResponse)(nil), // 35: kernloom.adapter.v1.ProvideAttestationEvidenceResponse
	(*Evidence)(nil),                           // 36: kernloom.adapter.v1.Evidence
	(*Finding)(nil),                            // 37: kernloom.adapter.v1.Finding
}
var file_kernloom_adapter_v1_adapter_proto_depIdxs = []int32{
	2,  // 0: kernloom.adapter.v1.DescribeResponse.adapter:type_name -> kernloom.adapter.v1.AdapterDescriptor
	3,  // 1: kernloom.adapter.v1.AdapterDescriptor.capabilities:type_name -> kernloom.adapter.v1.CapabilityDescriptor
	4,  // 2: kernloom.adapter.v1.AdapterDescriptor.context_requirements:type_name -> kernloom.adapter.v1.ContextRequirementDescriptor
	5,  // 3: kernloom.adapter.v1.AdapterDescriptor.privileges:type_name -> kernloom.adapter.v1.PrivilegeDescriptor
	10, // 4: kernloom.adapter.v1.PlanConfigResponse.proposed_changes:type_name -> kernloom.adapter.v1.ConfigChange
	10, // 5: kernloom.adapter.v1.ValidateConfigRequest.proposed_changes:type_name -> kernloom.adapter.v1.ConfigChange
	37, // 6: kernloom.adapter.v1.ValidateConfigResponse.findings:type_name -> kernloom.adapter.v1.Finding
	15, // 7: kernloom.adapter.v1.ReadObservedStateResponse.objects:type_name -> kernloom.adapter.v1.ObservedObject
	15, // 8: kernloom.adapter.v1.NormalizeStateRequest.objects:type_name -> kernloom.adapter.v1.ObservedObject
	15, // 9: kernloom.adapter.v1.NormalizeStateResponse.normalized_objects:type_name -> kernloom.adapter.v1.ObservedObject
	36, // 10: kernloom.adapter.v1.ProvideConformanceEvidenceResponse.evidence:type_name -> kernloom.adapter.v1.Evidence
	24, // 11: kernloom.adapter.v1.ReadSignalsResponse.signals:type_name -> kernloom.adapter.v1.Signal
	24, // 12: kernloom.adapter.v1.StreamSignalsResponse.signal:type_name -> kernloom.adapter.v1.Signal
	27, // 13: kernloom.adapter.v1.ProvideRelationshipsResponse.relationships:type_name -> kernloom.adapter.v1.Relationship
	36, // 14: kernloom.adapter.v1.ExecuteRuntimeActionResponse.evidence:type_name -> kernloom.adapter.v1.Evidence
	36, // 15: kernloom.adapter.v1.GetRuntimeActionStateResponse.evidence:type_name -> kernloom.adapter.v1.Evidence
	36, // 16: kernloom.adapter.v1.RevokeRuntimeActionResponse.evidence:type_name -> kernloom.adapter.v1.Evidence
	36, // 17: kernloom.adapter.v1.ProvideAttestationEvidenceResponse.evidence:type_name -> kernloom.adapter.v1.Evidence
	0,  // 18: kernloom.adapter.v1.AdapterService.Describe:input_type -> kernloom.adapter.v1.DescribeRequest
	6,  // 19: kernloom.adapter.v1.AdapterService.Health:input_type -> kernloom.adapter.v1.HealthRequest
	8,  // 20: kernloom.adapter.v1.AdapterService.PlanConfig:input_type -> kernloom.adapter.v1.PlanConfigRequest
	11, // 21: kernloom.adapter.v1.AdapterService.ValidateConfig:input_type -> kernloom.adapter.v1.ValidateConfigRequest
	13, // 22: kernloom.adapter.v1.AdapterService.ReadObservedState:input_type -> kernloom.adapter.v1.ReadObservedStateRequest
	16, // 23: kernloom.adapter.v1.AdapterService.NormalizeState:input_type -> kernloom.adapter.v1.NormalizeStateRequest
	18, // 24: kernloom.adapter.v1.AdapterService.ProvideConformanceEvidence:input_type -> kernloom.adapter.v1.ProvideConformanceEvidenceRequest
	20, // 25: kernloom.adapter.v1.AdapterService.ReadSignals:input_type -> kernloom.adapter.v1.ReadSignalsRequest
	22, // 26: kernloom.adapter.v1.AdapterService.StreamSignals:input_type -> kernloom.adapter.v1.StreamSignalsRequest
	25, // 27: kernloom.adapter.v1.AdapterService.ProvideRelationships:input_type -> kernloom.adapter.v1.ProvideRelationshipsRequest
	28, // 28: kernloom.adapter.v1.AdapterService.ExecuteRuntimeAction:input_type -> kernloom.adapter.v1.ExecuteRuntimeActionRequest
	30, // 29: kernloom.adapter.v1.AdapterService.GetRuntimeActionState:input_type -> kernloom.adapter.v1.GetRuntimeActionStateRequest
	32, // 30: kernloom.adapter.v1.AdapterService.RevokeRuntimeAction:input_type -> kernloom.adapter.v1.RevokeRuntimeActionRequest
	34, // 31: kernloom.adapter.v1.AdapterService.ProvideAttestationEvidence:input_type -> kernloom.adapter.v1.ProvideAttestationEvidenceRequest
	1,  // 32: kernloom.adapter.v1.AdapterService.Describe:output_type -> kernloom.adapter.v1.DescribeResponse
	7,  // 33: kernloom.adapter.v1.AdapterService.Health:output_type -> kernloom.adapter.v1.HealthResponse
	9,  // 34: kernloom.adapter.v1.AdapterService.PlanConfig:output_type -> kernloom.adapter.v1.PlanConfigResponse
	12, // 35: kernloom.adapter.v1.AdapterService.ValidateConfig:output_type -> kernloom.adapter.v1.ValidateConfigResponse
	14, // 36: kernloom.adapter.v1.AdapterService.ReadObservedState:output_type -> kernloom.adapter.v1.ReadObservedStateResponse
	17, // 37: kernloom.adapter.v1.AdapterService.NormalizeState:output_type -> kernloom.adapter.v1.NormalizeStateResponse
	19, // 38: kernloom.adapter.v1.AdapterService.ProvideConformanceEvidence:output_type -> kernloom.adapter.v1.ProvideConformanceEvidenceResponse
	21, // 39: kernloom.adapter.v1.AdapterService.ReadSignals:output_type -> kernloom.adapter.v1.ReadSignalsResponse
	23, // 40: kernloom.adapter.v1.AdapterService.StreamSignals:output_type -> kernloom.adapter.v1.StreamSignalsResponse
	26, // 41: kernloom.adapter.v1.AdapterService.ProvideRelationships:output_type -> kernloom.adapter.v1.ProvideRelationshipsResponse
	29, // 42: kernloom.adapter.v1.AdapterService.ExecuteRuntimeAction:output_type -> kernloom.adapter.v1.ExecuteRuntimeActionResponse
	31, // 43: kernloom.adapter.v1.AdapterService.GetRuntimeActionState:output_type -> kernloom.adapter.v1.GetRuntimeActionStateResponse
	33, // 44: kernloom.adapter.v1.AdapterService.RevokeRuntimeAction:output_type -> kernloom.adapter.v1.RevokeRuntimeActionResponse
	35, // 45: kernloom.adapter.v1.AdapterService.ProvideAttestationEvidence:output_type -> kernloom.adapter.v1.ProvideAttestationEvidenceResponse
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_kernloom_adapter_v1_adapter_proto_init() }
func file_kernloom_adapter_v1_adapter_proto_init() {
	if File_kernloom_adapter_v1_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernloom_adapter_v1_adapter_proto_rawDesc), len(file_kernloom_adapter_v1_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernloom_adapter_v1_adapter_proto_goTypes,
		DependencyIndexes: file_kernloom_adapter_v1_adapter_proto_depIdxs,
		MessageInfos:      file_kernloom_adapter_v1_adapter_proto_msgTypes,
	}.Build()
	File_kernloom_adapter_v1_adapter_proto = out.File
	file_kernloom_adapter_v1_adapter_proto_goTypes = nil
	file_kernloom_adapter_v1_adapter_proto_depIdxs = nil
}
